name: General checks

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  check-code:
    uses: ./.github/workflows/tmp-check-code.yml
    with:
      actions-ref: ${{ github.sha }}  # use local version

  check-schema:
    uses: ./.github/workflows/tmp-check-schema.yml
    with:
      azure-dir: '' # disable azure checks

  check-package:
    uses: ./.github/workflows/tmp-check-package.yml
    with:
      import-name: "lightning_mingpt"
      artifact-name: "lightning-mingpt"
      testing-matrix: |
        {
          "os": ["ubuntu-20.04", "macos-11", "windows-2022"],
          "python-version": ["3.8", "3.10"]
        }
